@startuml
' Диаграмма деятельности: процесс бронирования оборудования
start

:Просмотр каталога;

:Выбор оборудования\nи дат аренды;

:Проверка доступности;

if (Доступно?) then (да)
  :Добавление в корзину;

  :Оформление заказа;

  :Ввод платежных данных;

  :Обработка платежа;

  if (Платеж успешен?) then (да)
    :Создание бронирования;

    :Отправка подтверждения\nклиенту;

    :Уведомление склада;

    stop
  else (нет)
    :Сообщение об ошибке;
    stop
  endif
else (нет)
  :Предложение альтернатив;
  stop
endif

@enduml
